server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
    database: 1
    password:
  # JavaMailSender 邮件发送的配置
  mail:
    host: smtp.139.com
    username: xx@139.com
    password: xx
    test-connection: false
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        imap:
          ssl:
            socketFactory:
              fallback: false
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              class: com.fintech.modules.base.util.mail.MailSSLSocketFactor

jusic:
  music-expire-time: 1200000
  rtry-count: 1
  vote-rate: 0.3
  default-music-file: 'http://www.alang.run/default-list.txt' #classpath:music/default-list.txt classpath:music/default-list.txt
  music-serve-domain: 'http://127.0.0.1:8888'
  music-serve-domain_qq: 'http://127.0.0.1:3300'
  music-serve-domain_mg: 'http://127.0.0.1:3400'#'http://localhost:3400'#
  mail-send-from: 'xx@139.com'
  mail-send-to: 'xx@qq.com'
  serverJUrl: 'https://sc.ftqq.com/xx.send'

